package com.example.bookyourtoken.ui.theme

import androidx.compose.ui.graphics.Color

// Warm "saffron" palette — light scheme
val PrimaryLight = Color(0xFF9A4521)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFFFDBCC)
val OnPrimaryContainerLight = Color(0xFF360F00)
val SecondaryLight = Color(0xFF77574A)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFFFDBCC)
val OnSecondaryContainerLight = Color(0xFF2C160C)
val TertiaryLight = Color(0xFF67602F)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFEFE5A7)
val OnTertiaryContainerLight = Color(0xFF1F1C00)
val BackgroundLight = Color(0xFFFFF8F6)
val SurfaceLight = Color(0xFFFFF8F6)
val OnSurfaceLight = Color(0xFF221A16)
val SurfaceVariantLight = Color(0xFFF5DED6)
val OnSurfaceVariantLight = Color(0xFF53433E)
val OutlineLight = Color(0xFF85736D)
val OutlineVariantLight = Color(0xFFD8C2BA)
val SurfaceContainerLowLight = Color(0xFFFFF1EC)
val SurfaceContainerLight = Color(0xFFFCEAE4)
val SurfaceContainerHighLight = Color(0xFFF6E4DE)
val SurfaceContainerHighestLight = Color(0xFFF0DFD8)

// Dark scheme
val PrimaryDark = Color(0xFFFFB693)
val OnPrimaryDark = Color(0xFF571F00)
val PrimaryContainerDark = Color(0xFF7B2F0B)
val OnPrimaryContainerDark = Color(0xFFFFDBCC)
val SecondaryDark = Color(0xFFE7BDAD)
val OnSecondaryDark = Color(0xFF442A1F)
val SecondaryContainerDark = Color(0xFF5D4034)
val OnSecondaryContainerDark = Color(0xFFFFDBCC)
val TertiaryDark = Color(0xFFD2C98D)
val OnTertiaryDark = Color(0xFF363105)
val TertiaryContainerDark = Color(0xFF4E4819)
val OnTertiaryContainerDark = Color(0xFFEFE5A7)
val BackgroundDark = Color(0xFF1A110E)
val SurfaceDark = Color(0xFF1A110E)
val OnSurfaceDark = Color(0xFFF1DFD8)
val SurfaceVariantDark = Color(0xFF53433E)
val OnSurfaceVariantDark = Color(0xFFD8C2BA)
val OutlineDark = Color(0xFFA08D86)
val OutlineVariantDark = Color(0xFF53433E)
val SurfaceContainerLowDark = Color(0xFF231915)
val SurfaceContainerDark = Color(0xFF271D19)
val SurfaceContainerHighDark = Color(0xFF322823)
val SurfaceContainerHighestDark = Color(0xFF3D322D)

// Semantic "booked / success" colours, not part of the M3 scheme
val SuccessLight = Color(0xFF2E7D32)
val SuccessDark = Color(0xFF81C784)
val SuccessContainerLight = Color(0xFFD7F0D8)
val OnSuccessContainerLight = Color(0xFF0B3D12)
val SuccessContainerDark = Color(0xFF1F3A23)
val OnSuccessContainerDark = Color(0xFFC3EBC6)
